server:
  port: 8888
spring:
  application:
    name: configurationserver
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: /respo/{application}/
          username: junjun.zhu
          password: junjun.zhu
      label: develop
logging:
  level:
    ROOT: INFO
    org.junyee.microserivce: DEBUG
    org.springframework.cloud: DEBUG

