server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/o0junyee0o/microservice.git
          search-paths: /config-repo/{application}/
          username:
          password:
      label: master
    bus:
      trace:
        enabled: true
      enabled: true
      refresh:
        enabled: true
    consul:
        host: www.junyee.org
        port: 8500
        discovery:
          health-check-url: http://www.junyee.org:8888/actuator/health
          healthCheckInterval: 15s
          instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  zipkin:
    base-url: http://www.junyee.org:9411/
    service:
      name: configuration-server
    locator:
      discovery:
        enabled: true
    sender:
      type: web
  rabbitmq:
    host: www.junyee.org
    port: 5672
    username: guest
    password: guest
logging:
  level:
    ROOT: INFO
    org.junyee.microserivce: DEBUG
    org.springframework.cloud: DEBUG
management:
  endpoint:
    bus-refresh:
      enabled: true
    hystrix:
      config:

  endpoints:
    web:
      exposure:
        include: ["health","info","bus-refresh"]



