server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/o0junyee0o/microservice.git
          search-paths: /config-repo/{application}/
          username:
          password:
      label: master
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: www.junyee.org
    port: 5672
    username: guest
    password: guest
logging:
  level:
    ROOT: INFO
    org.junyee.microserivce: DEBUG
    org.springframework.cloud: DEBUG


