server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/o0junyee0o/microservice.git
          search-paths: /config-repo/{application}/
          username:
          password:
      label: master
logging:
  level:
    ROOT: INFO
    org.junyee.microserivce: DEBUG
    org.springframework.cloud: DEBUG

